name: Lint
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: yarn
    - name: Run ESLint
      run: yarn lint
